# setup.cfg

[metadata]
name = plover-yawei-tiger
version = 1.1.0
description = Chinese Yawei+tiger chorded input system for Plover
author = r3n4ive
author_email = 5531047+r3n4ive@users.noreply.github.com
url = https://github.com/r3n4ive/plover-yawei-tiger
license = MIT
keywords = plover_plugin, plover, steno, yawei, rime
classifiers =
    Environment :: Plugins
    Intended Audience :: End Users/Desktop
    Operating System :: Microsoft :: Windows
    Programming Language :: Python :: 3

[options]
packages = find:
include_package_data = True
install_requires =
    plover>=4.0.0
    hidapi

[options.package_data]
plover_yawei_tiger =
    dictionaries/*.json
    theory_map/*.txt
    rime_data/*.yaml

[options.entry_points]
plover.system =
    yawei-tiger = plover_yawei_tiger.system
plover.machine =
    Yawei V3 = plover_yawei_tiger.machine:YaweiV3
plover.extension =
    yawei-rime = plover_yawei_tiger.extension:YaweiRimeExtension
