# setup.cfg

[metadata]
name = plover-yawei-tiger
version = 1.0.0
description = Chinese Yawei+tiger chorded input system for Plover
author = 寝
license = MIT

[options]
packages = find:
include_package_data = True
install_requires =
    plover>=4.0.0
    hidapi

[options.entry_points]
plover.system =
    yawei-tiger = plover_yawei_tiger.system
plover.machine =
    Yawei V3 = plover_yawei_tiger.machine:YaweiV3
